# Generated by Django 3.0.6 on 2020-07-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_remove_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол'),
        ),
    ]
