# Generated by Django 3.1.4 on 2021-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('message', models.TextField(null=True, verbose_name='Текст')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='img',
            field=models.ImageField(null=True, upload_to='feedback/images', verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
