# Generated by Django 3.1.4 on 2021-03-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0008_auto_20210309_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=300, verbose_name='Баланс'),
        ),
    ]
