# Generated by Django 3.0.6 on 2020-06-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='about_zh_cn',
            new_name='about_zh_hans',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='rules_zh_cn',
            new_name='rules_zh_hans',
        ),
    ]
