# Generated by Django 3.0.6 on 2020-06-28 18:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200622_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфо'),
        ),
        migrations.AddField(
            model_name='settings',
            name='info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфо'),
        ),
        migrations.AddField(
            model_name='settings',
            name='info_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфо'),
        ),
        migrations.AddField(
            model_name='settings',
            name='info_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инфо'),
        ),
    ]
