# Generated by Django 3.0.6 on 2020-05-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='level',
            new_name='lev',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='level',
            new_name='lev',
        ),
    ]
