# Generated by Django 3.0.6 on 2020-05-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200513_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='lev',
        ),
    ]
