# Generated by Django 2.2.7 on 2020-05-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200517_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameImage'),
        ),
    ]
