# Generated by Django 2.2.7 on 2020-05-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_game_type_2_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type_2_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_image',
        ),
    ]
