# Generated by Django 2.2.7 on 2020-06-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200517_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='size_x',
        ),
        migrations.RemoveField(
            model_name='level',
            name='size_y',
        ),
        migrations.RemoveField(
            model_name='level',
            name='time',
        ),
        migrations.RemoveField(
            model_name='level',
            name='title',
        ),
        migrations.AddField(
            model_name='level',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='+баланс в %'),
        ),
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='level',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='+рейтинг в %'),
        ),
        migrations.AddField(
            model_name='level',
            name='timer',
            field=models.IntegerField(default=0, verbose_name='Таймер в минутах'),
        ),
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Level'),
        ),
    ]
