# Generated by Django 3.0.6 on 2020-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200610_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='+рейтинг'),
        ),
    ]
